version: '3.2'

services:

  nginx:
    image: namelessmc/nginx:REPLACEME_VERSION
    extra_hosts: ['database:10.0.6.2']
    networks:
      namelessmc_proxy:
        ipv4_address: REPLACEME_IPADDR
    volumes:
      - type: bind
        source: ./web
        target: /data
        read_only: true
    environment:
      PHP_FPM: localhost:9000
    restart: always

  php:
    image: namelessmc/php:REPLACEME_VERSION
    volumes:
      - type: bind
        source: ./web
        target: /data
    network_mode: 'service:nginx'
    environment:
      NAMELESS_HOSTNAME: REPLACEME_HOSTNAME
      NAMELESS_DATABASE_ADDRESS: database
      NAMELESS_DATABASE_NAME: site_REPLACEME_SITEID
      NAMELESS_DATABASE_USERNAME: user_REPLACEME_SITEID
      NAMELESS_DATABASE_PASSWORD: REPLACEME_DBPASSWORD
      NAMELESS_FRIENDLY_URLS: 'true'
      # NAMELESS_SITE_NAME: REPLACEME_SITENAME
      # NAMELESS_SITE_CONTACT_EMAIL: REPLACEME_EMAIL
      # NAMELESS_SITE_OUTGOING_EMAIL: REPLACEME_EMAIL
      # NAMELESS_ADMIN_USERNAME: REPLACEME_USERNAME
      # NAMELESS_ADMIN_EMAIL: REPLACEME_EMAIL
    restart: always

networks:
  namelessmc_proxy:
    external: true
