version: '3'

services:

  nginx:
    image: namelessmc/nginx
    networks:
      default:
      namelessmc_proxy:
        ipv4_address: REPLACEME_IPADDR
    volumes: ['./web:/data:ro']
    depends_on: [php]
    restart: always

  php:
    image: namelessmc/php:REPLACEME_VERSION
    volumes: ['./web:/data']
    depends_on: [database]
    restart: always

  database:
    image: mariadb
    volumes: ['./db:/var/lib/mysql']
    environment:
      MYSQL_ROOT_PASSWORD: REPLACEME_DBPASSWORD
      MYSQL_DATABASE: nameless
    restart: always

  phpmyadmin:
    image: nlmc_hosting/phpmyadmin
    network_mode: service:nginx
    volumes: [/sessions]
    depends_on: [database]
    environment:
      PMA_HOST: database
      PMA_ABSOLUTE_URI: REPLACEME_PHPMYADMINURI
    restart: always

networks:
  namelessmc_proxy:
    external: true
